import {tech,media,archive} from './data.js';
export const mediaFilters=['全部','影音剪輯','實地探訪','國際合作企劃'];
export const techFilters=['全部','Web 開發','App 開發','AI 與自動化專案'];
export const mediaWorks=[
 {...media[0],category:'影音剪輯',youtube:'gnnFXbROSfs',role:'編劇 / 導演 / 剪輯'},
 {...media[1],category:'影音剪輯',role:'提案企劃 / 剪輯'},
 {...media[2],title:'LINE FRESH 品牌與數位經營企劃',subtitle:'從地方故事，規劃品牌的數位表達。',description:'透過嘉義與花蓮的田野訪談及店家溝通，梳理品牌特色與經營需求，規劃地方故事與影音內容；推廣 LINE 官方帳號，推動品牌形象建立與數位經營轉譯，並協作完成拍攝與剪輯。',result:'嘉義 × 花蓮 · 品牌故事與數位經營企劃',category:'實地探訪',image:'assets/img/嘉義.png',role:'品牌企劃 / 店家溝通 / 官方帳號推廣 / 影音製作',slides:'1ZSMijQbHxh9DbUH2Shxb5vAmeZLsDA06ixulhRhXMiQ',links:[['花蓮與地方創生簡報','https://docs.google.com/presentation/d/1dQW35-lPEr60iyN_PQqscWSzsVcKt31_evMIh7qw3SQ/edit'],['今天就回嘉官方帳號','https://liff.line.me/1645278921-kWRPP32q/?accountId=homechiayi'],['LINE FRESH 結訓紀錄','https://www.facebook.com/share/p/jAP98NvrnndmzACE/']]},
 {id:'maori',title:'文化開解所：紐西蘭見習',subtitle:'讓文化保存，走向可以參與的學習。',category:'國際合作企劃',type:'INTERNATIONAL / 2025',tags:['文化研究','國際交流','計畫提案'],image:'assets/portfolio/p3-2.jpg',description:'獲選青年百億海外圓夢計畫，走訪紐西蘭毛利文化場域，探索臺灣原住民族文化數位平台、智慧導覽與社群共創。',role:'計畫提案 / 文化見習與研究',result:'青年百億海外圓夢計畫獲選',url:'https://docs.google.com/document/d/1Zo5cYw6oA3yXXkN8xNkP0tBimMmMfxcHyPc5m4_CrAY/edit',linkLabel:'閱讀完整計畫',gallery:['assets/portfolio/p3-1.png'],note:'國際見習與平台規劃；數位平台尚非已上線產品。'},
 {id:'temple',title:'景美集應廟文化發展研究',subtitle:'走進地方，從訪談理解文化的變遷。',category:'實地探訪',type:'CULTURE / QUALITATIVE RESEARCH',tags:['深度訪談','田野觀察','質性編碼'],image:'assets/portfolio/p4-0.png',description:'領導小組結合文獻、田野觀察與深度訪談，研究廟宇歷史、建築藝術及文化傳承，並以影像留下研究紀錄。',role:'小組領導 / 訪談 / 質性資料分析',result:'7 位資深導覽員訪談 · 逐字稿與開放編碼',url:'https://docs.google.com/document/d/1PnhgkMrCj5ovawIuk37fCMEnpIuY6Zet/edit',linkLabel:'閱讀研究報告',driveVideo:'1B-mcc2gQwVq8lzTc5bCMUAxlWRb-4R3V',gallery:['assets/portfolio/p4-1.png','assets/portfolio/p4-2.png','assets/portfolio/p4-3.png']},
 {id:'96minutes',title:'電影《96 分鐘》合作企劃與宣傳製作',subtitle:'從合作洽談到宣傳素材，參與電影行銷執行。',category:'視覺設計',type:'FILM MARKETING / 2025',tags:['合作企劃','異業合作','貼紙設計'],image:'assets/portfolio/p17-7.png',description:'參與華影《96 分鐘》電影行銷，進行合作企劃洽談與異業合作接洽，協助整理合作方向及宣傳內容；同時發想與製作電影宣傳貼紙，將電影情境延伸為可運用的視覺素材。',role:'合作企劃洽談 / 異業合作接洽 / 宣傳素材製作',result:'合作企劃與宣傳素材製作實作',gallery:['assets/portfolio/p17-0.png','assets/portfolio/p17-1.png','assets/portfolio/p17-2.png','assets/portfolio/p17-3.png','assets/portfolio/p17-6.png']},
 {...media[3],category:'影音剪輯',youtube:'GmhME2BlwaQ',role:'Blender 場景 / 角色 / 材質 / 燈光',gallery:['assets/平面設計/fire-n.png','assets/平面設計/fire-w.png']},
 ...archive.slice(0,4).map(([title,type,image,url],i)=>({id:`line-film-${i}`,title,category:'實地探訪',type:'LINE FRESH / SHORT FILM',image,url,linkLabel:'前往 LINE VOOM 觀看',description:'LINE FRESH 嘉義地方影音作品，透過走訪與影像製作，介紹店家與在地故事。',role:'團隊影音企劃與製作',tags:['LINE FRESH','短影音'],result:'地方品牌數位敘事'})),
 ...archive.slice(4,8).map(([title,type,image,url],i)=>({id:`film-${i}`,title,category:'影音剪輯',type:'FILM / MOTION',image,url,linkLabel:'觀看完整影片',youtube:['6G2gxYVADWc','AKUj2WgPr9w','CzO935-kiLg','_E63GVTv7M0'][i],description:['紀錄宜蘭三天兩夜的旅遊與住宿體驗，透過剪輯組織日常片段。','透過簡單對白與不尋常的人物互動，創作帶有幽默感的劇情短片。','以動畫介紹電子競技的起源與相關比賽方式，練習資訊轉譯與節奏設計。','世新傳技展劇情短片，首次擔任導演拍攝約十分鐘作品，累積敘事與現場協作經驗。'][i],tags:[type],role:i===3?'導演':'影音創作',result:'自主／課程創作'})),
 {id:'graphic',title:'平面設計選集',category:'視覺設計',type:'GRAPHIC / EXPLORATIONS',image:'assets/平面設計/food.png',description:'從 LOGO、貼圖、桌面背景到畢業紀念冊，持續探索圖像、字體與配色的組合。',tags:['識別設計','視覺編排'],url:archive[8][3],linkLabel:'查看設計選集',gallery:['assets/平面設計/lo-17.png','assets/平面設計/gg.png','assets/平面設計/salar.png'],role:'平面設計'},
 {id:'motion',title:'After Effects 動態實驗',category:'影音剪輯',type:'MOTION / SELF-DIRECTED',image:'assets/平面設計/gg.png',video:'assets/video/water1.mp4',description:'自主學習 After Effects，製作動畫練習，並將動態設計技巧運用於影音剪輯。',tags:['After Effects','Motion'],url:archive[9][3],linkLabel:'觀看動畫播放清單',role:'動畫設計'},
 {id:'wolf',title:'怪物頭顱建模紀錄',category:'影音剪輯',type:'3D / PROCESS',image:'assets/平面設計/blender.png',video:'assets/video/wolf.mp4',description:'從參考圖片出發，以半透明對照建立頭部模型，搭配材質與眼睛發光效果，記錄建模過程。',tags:['Blender','建模縮時'],role:'3D 建模與製作紀錄'}
];
export const techWorks=[
 {...tech[0],github:'https://github.com/shuda0920/RightWay',detail:tech[0].detail.replace('原始碼尚未公開。',''),category:'App 開發',categories:['App 開發','AI 與自動化專案'],image:'assets/portfolio/p2-2.png',gallery:['assets/portfolio/p2-3.png','assets/portfolio/p2-0.png','assets/portfolio/p2-1.png'],url:'https://docs.google.com/document/d/1azVmvpNEGGL6obueuWncfAWp-AOcHfjp/edit',linkLabel:'閱讀開發報告',pain:'旅遊資訊過多，使用者難以把模糊的偏好轉成行程選擇。',flow:['約 3,000 筆景點資料','分類標註與中文嵌入','向量檢索 + LLM','Flutter 滑卡推薦'],note:'開發原型；可由 GitHub 查看程式碼，尚未提供安裝下載。'},
 {...tech[1],github:'https://github.com/Scorpio-meow/AskMiao',category:'AI 與自動化專案',image:'assets/portfolio/p7-3.png',pain:'單一模型觀點有限，回應需要文件依據與不同角色的交互檢視。',flow:['文件知識庫','RAG 檢索','多角色 Agent 協作','回應整合與測試'],note:'MVP 實驗；GitHub 專案為 AskMiao，未提供 Live Demo。'},
 {id:'gender-web',title:'北一區性平教育中心',subtitle:'讓教育資源，有清楚的資訊入口。',category:'Web 開發',type:'WEB / EDUCATION',tags:['Google Sites','資訊架構','教育內容'],image:'assets/portfolio/p16-0.png',description:'參與北一區大專校院性別平等教育工作推展中心網站建置，呈現教育資源與相關訊息。',role:'網站建置',pain:'教育推廣資訊需要集中呈現，協助訪客找到所需資源。',flow:['內容整理','頁面與導覽規劃','Google Sites 網站建置'],url:'https://sites.google.com/mail.shu.edu.tw/northerndistrict1-gendercenter',linkLabel:'瀏覽網站',note:'連結為既有網站，目前內容由網站管理單位維護。'},
 {id:'speech-web',title:'世新口傳系網站翻新',subtitle:'以網站整理系所的對外溝通。',category:'Web 開發',type:'WEB / REDESIGN',tags:['網站翻新','內容呈現','資訊組織'],image:'assets/portfolio/p16-1.png',description:'參與世新大學口語傳播暨社群媒體學系網站翻新，整理系所資訊的呈現方式。',role:'系所網站翻新',pain:'系所資訊需要更清楚的頁面呈現，支援訪客瀏覽與理解。',flow:['既有內容盤點','頁面更新','資訊呈現調整'],url:'https://speech.shu.edu.tw/',linkLabel:'瀏覽系所網站',note:'連結為現行系所網站；作品集未載明完整技術棧與原始碼。'},
 {...tech[2],category:'App 開發',pain:'健身使用者的需求與操作痛點，需要先透過訪談釐清。',flow:['質性研究訪談','痛點分析','介面流程設計','Figma 互動原型'],note:'UX 原型，非可安裝 App；可播放操作預覽或開啟 Figma。'},
 {id:'pedestrian',title:'「行人地獄」媒體敘事研究',category:'AI 與自動化專案',type:'RESEARCH / PROPOSAL',tags:['AI 文本分析','NLP 構想','研究設計'],description:'研擬結合 AI 文本分析與數據挖掘，探討媒體敘事、社會認知與政策反應的關係。',role:'研究計畫研擬',pain:'媒體敘事如何影響交通安全認知，需要有系統的資料與方法來檢驗。',flow:['研究問題設定','文獻回顧','文本分析方法規劃','可行性反思'],result:'國科會計畫研擬 · 未獲通過',note:'未獲通過的研究提案；保留方法反思，非已驗證的研究結果。',url:'https://docs.google.com/document/d/1e2dc-54svCDzrf4P8bCghhM2ZA2Cqk3y/edit',linkLabel:'閱讀研究提案'}
];
export const experience=[
 ['2025 — 2026','神通資訊 MITAC','AI 程式設計實習生','參與多代理人 RAG 對話 MVP 開發與測試，研究 AI 應用及 PoC。透過功能測試、競品研究與使用情境分析，評估產品可行性並提出優化建議。','tech.html#rag'],
 ['2023 — 2024','LINE Taiwan · LINE FRESH','數位成長實習生 · 企劃與數位經營','走訪嘉義與花蓮，透過田野訪談與店家溝通梳理品牌特色及經營需求，規劃地方故事與影音內容。推廣 LINE 官方帳號，推動地方故事、品牌形象建立與數位經營轉譯，並協作完成拍攝與剪輯，讓企劃落實為可使用的宣傳內容。','proo.html#line'],
 ['2025','華影國際影藝 ·《96 分鐘》','電影行銷實習 · 合作企劃與宣傳製作','參與《96 分鐘》電影行銷，進行合作企劃洽談與異業合作接洽，協助整理合作方向及宣傳內容。同時發想與製作電影宣傳貼紙，將電影情境轉化為視覺素材，累積從對外溝通、企劃討論到宣傳製作的實作經驗。','proo.html#96minutes'],
];
